version: '3'

services:
  db:
    image: postgres:14-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=vijay
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ginrest
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local